### ISSUE TITLE
Test iOS version

### ISSUE THREAD

**Issue by doolse** [doolse/purescript-reactnative-example#2]
Changed the way the purescript is built slightly (mainsrc folder) and upgraded the libraries, so needs testing on iOS again. @sectore you might be interested?

**Comment by sectore** [comment]
Sure. Will do it within next few days (probably next weekend).

**Comment by sectore** [comment]
Looks great on `iOS` - thanks for the updates!

**Comment by doolse** [comment]
Thanks :+1:
