### ISSUE TITLE
OSS license.

### ISSUE THREAD

**Issue by adamczykm** [doolse/purescript-reactnative-example#8]
In my opinion this project should be released with an OSS license, because, apparently, Github's policy is to apply default copyrights laws which prevents any derivative works.
"If there's no license or permission, it's not open source, and others are not allowed to use it let alone change or redistribute it." - from https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by paluh** [comment]
@doolse We are really interested in contributing to your purescript libraries (this lib and `purescript-reactnative`), but it could be hard without knowledge of licensing terms. Could you tell us what kind of license are going to add to this projects?

**Comment by doolse** [comment]
Hi @adamczykm @paluh, I've added the MIT license to these two projects. BTW I don't have a lot of time to dedicate to these libraries at the moment as I'm not doing React native apps at the moment but I will certainly merge pull requests or even give people owner access if anyone is willing.

**Comment by paluh** [comment]
@doolse Thanks!
